# Generated by Django 5.1.5 on 2025-02-01 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('codigo_nfc', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja')], default='activo', max_length=10)),
                ('informacion_adicional', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_empleados/')),
                ('rol', models.CharField(choices=[('Oficina', 'Oficina'), ('Direccion', 'Direccion'), ('Tecnico', 'Tecnico')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_oferta', models.CharField(editable=False, max_length=6, unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('inicio_conversacion', 'Inicio de la conversación'), ('oferta_enviada', 'Oferta enviada'), ('esperando_respuesta', 'Esperando respuesta'), ('cancelada', 'Cancelada'), ('aprobada', 'Aprobada')], default='inicio_conversacion', max_length=25)),
                ('persona_responsable', models.ForeignKey(limit_choices_to={'rol__in': ['Oficina', 'Direccion']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_responsable', to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_estado', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(choices=[('inicio_conversacion', 'Inicio de la conversación'), ('oferta_enviada', 'Oferta enviada'), ('esperando_respuesta', 'Esperando respuesta'), ('cancelada', 'Cancelada'), ('aprobada', 'Aprobada')], max_length=25)),
                ('importe_euros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documento', models.FileField(blank=True, null=True, upload_to='historico_ofertas_documentos/')),
                ('url', models.URLField(blank=True, null=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='core.oferta')),
            ],
            options={
                'ordering': ['-fecha_creacion_estado'],
            },
        ),
    ]
