# Generated by Django 5.1.5 on 2025-02-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='persona_responsable',
        ),
        migrations.RemoveField(
            model_name='historicooferta',
            name='oferta',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='HistoricoOferta',
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
