# Generated by Django 5.1.5 on 2025-03-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amazon_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
