# Generated by Django 5.1.5 on 2025-05-17 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('collaborative', 'Filtrado Colaborativo'), ('content', 'Content-Based'), ('svd', 'SVD Matrix Factorization'), ('knn', 'K-Nearest Neighbors'), ('hybrid', 'Híbrido')], max_length=30)),
                ('metric', models.CharField(choices=[('rmse', 'RMSE'), ('mae', 'MAE'), ('precision', 'Precision@K'), ('recall', 'Recall@K'), ('ctr', 'Click Through Rate'), ('avg_cart_value', 'Valor Medio Carrito')], max_length=30)),
                ('value', models.FloatField()),
                ('k_value', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluación de Algoritmo',
                'verbose_name_plural': 'Evaluaciones de Algoritmos',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
